packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - bullmq@6.3.12
  - basic-ftp@6.2.3
overrides:
  deepmerge-ts@7.1.5: 8.0.2
  tmp: 0.2.7
  basic-ftp: 6.2.3
